#!/bin/sh

#   my Notes for debmirror setup
# ============================
#
#   debmirror script files:
#     debmirror_debian.sh
#     debmirror_debian-security.sh
#     debmirror_sync_mirror
#     user_get_gpg_keys.sh
#
#   #: adduser m
#   #: mkdir -p /srv/dmirror
#   #: chown m:m -R /srv/dmirror
#
#   su - m
#     mkdir bin/
#     setup .bashrc: add PATH ~/bin/, add alias ll=ls -la, add PATH sbin(s)/
#     add debmirror script files to bin/
#     setup ssh, vim, what-ever...
#     run user_get_pgp_keys.sh
#
# ============================

allowed_user=m

if [ "$USER" != "$allowed_user" ]; then
    echo "Abort, wrong user: $USER"
    exit 1
fi

echo
echo "debmirror sync debian..."
debmirror_debian.sh

echo
echo "debmirror sync debian-security..."
debmirror_debian-security.sh

echo
echo "vdr-checksums checksum size..."
vdr-chksums -r /srv/dmirror/

# ***
