Document: vdr-chksums
Title: Debian vdr-chksums Manual
Author: <insert document author here>
Abstract: This manual describes what vdr-chksums is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vdr-chksums/vdr-chksums.sgml.gz

Format: postscript
Files: /usr/share/doc/vdr-chksums/vdr-chksums.ps.gz

Format: text
Files: /usr/share/doc/vdr-chksums/vdr-chksums.text.gz

Format: HTML
Index: /usr/share/doc/vdr-chksums/html/index.html
Files: /usr/share/doc/vdr-chksums/html/*.html
